project_name: sctool
release:
  github:
    owner: marianogappa
    name: sctool
brew:
  install: bin.install "sctool"
builds:
- goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  main: .
  ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  env:
    - CGO_ENABLED=0
    - GO111MODULE=on
